---
dist: trusty
sudo: true
language: ruby
before_script:
  - bundle install
  - bundle exec puppet --version
  - bundle exec puppet module build
  - bundle exec puppet module install pkg/*.tar.gz
  - sudo sed -i 's/main$/& contrib non-free/' /etc/apt/sources.list
  - sudo apt update
  - sudo apt install conserver-server conserver-client -y   
  - conserver -v
  - mkdir -p /tmp/conserver
script:
  - bundle exec rake validate
  - bundle exec rake syntax lint
  - bundle exec rake metadata_lint
  - bundle exec rake spec
  - 'sudo -E env PATH=$PATH bundle exec puppet module install pkg/*.tar.gz'
  - 'sudo -E env PATH=$PATH bundle exec puppet --version'
  - 'sudo -E env PATH=$PATH bundle exec ./smoke/test -d'
rvm:
  - 2.1.9
  - 2.3.4
  - 2.4.1
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 4.9.1" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 4.10.10" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 5.0.0" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 5.4.0" FIXTURES_YML=.fixtures.yml
    - PUPPET_GEM_VERSION="~> 5.5.0" FIXTURES_YML=.fixtures.yml
matrix:
  fast_finish: true
  exclude:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 5.5.0" FIXTURES_YML=.fixtures.yml
 

